[[plugins]]
repo = 'Shougo/vimproc.vim'
  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  cygwin  = 'make -f make_cygwin.mak'
  mac     = 'make -f make_mac.mak'
  unix    = 'make -f make_unix.mak'

[[plugins]]
repo    = 'Shougo/unite.vim'
depends = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'banyan/recognize_charcode.vim'

[[plugins]]
repo = 'deton/jasegment.vim'

[[plugins]]
repo = 'glidenote/memolist.vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'kmnk/vim-unite-giti'

[[plugins]]
repo = 'moll/vim-node'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
rev  = 'ac9f4be0698dffb30ebdf284f8ba5abbaab5eaca'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'vim-scripts/grep.vim'

[[plugins]]
repo = 'vim-scripts/gtags.vim'

[[plugins]]
repo = 'rhysd/vim-operator-surround'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo     = 'Shougo/neocomplete.vim'
depends  = 'Shougo/context_filetype.vim'

[[plugins]]
repo     = 'Shougo/context_filetype.vim'

[[plugins]]
repo     = 'Shougo/neosnippet-snippets'


#--------------------------------
# Syntax check
#--------------------------------
[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'

[[plugins]]
repo = 'KazuakiM/vim-qfsigns'

[[plugins]]
repo = 'dannyob/quickfixstatus'


#--------------------------------
# Color scheme
#--------------------------------
[[plugins]]
repo = 'ujiro99/my_color_scheme'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'
